#!/bin/bash -e
#
# ToDo:
# * flush and load ipset's
#
BASEDIR=/etc/firewall
POLV4="${BASEDIR}"/firewall-ipv4.fw
POLV6="${BASEDIR}"/firewall-ipv6.fw
IPSETC="${BASEDIR}"/ipset-create
IPSETI="${BASEDIR}"/ipset-items

backup="$(mktemp)"

case "$1" in
"start")
   test -e "$IPSETC" && . "$IPSETC"
   test -e "$IPSETI" && { ipset save > "$backup"; ipset restore < "$IPSETI" || { ipset restore < "$backup" ; exit 1; } }
   test -e "$POLV4" && { iptables-save > "$backup"; iptables-restore "$POLV4" || { iptables-restore "$backup"; exit 1; } }
   test -e "$POLV6" && { ip6tables-save > "$backup"; ip6tables-restore "$POLV6" || { ip6tables-restore "$backup"; exit 1; } }
   ;;
"stop")
   for chain in INPUT FORWARD OUTPUT; do
      test -e "$POLV4" && { iptables -P "$chain" ACCEPT; iptables -F "$chain"; }
      test -e "$POLV6" && { ip6tables -P "$chain" ACCEPT; ip6tables -F "$chain"; }
   done
   ;;
*)
   echo "Usage: $0 <stop|start>"
   exit 1
   ;;
esac
rm -f "$backup"
test "$NOTIFY_SOCKET" != "" && systemd-notify READY=1
exit 0
