#!/usr/bin/env bash

# Extract and validate Container ID
PCTID="${USER/ct/}"
re='^[0-9]+$'

if ! [[ "$PCTID" =~ $re ]] || [ "$PCTID" -lt 1 ] || [ "$PCTID" -gt 65565 ]; then
    echo "Error: Invalid container ID." >&2
    exit 1
fi

# Handle SFTP
if [[ "$SSH_ORIGINAL_COMMAND" == */sftp-server* ]] || [[ "$SSH_ORIGINAL_COMMAND" == *internal-sftp* ]]; then
    exec /usr/bin/sudo /usr/bin/lxc-attach -n "${PCTID}" --clear-env -- /bin/su - root -c '
        if [ -x /usr/lib/openssh/sftp-server ]; then
            exec /usr/lib/openssh/sftp-server
        elif [ -x /usr/libexec/openssh/sftp-server ]; then
            exec /usr/libexec/openssh/sftp-server
        else
            echo "SFTP server not found." >&2
            exit 1
        fi
    '
# Handle Arbitrary Commands (SCP, one-off commands)
elif [[ -n "$SSH_ORIGINAL_COMMAND" ]]; then
    exec /usr/bin/sudo /usr/bin/lxc-attach -n "${PCTID}" --clear-env \
        -- /bin/su - root -c "${SSH_ORIGINAL_COMMAND}"

# Handle Interactive Sessions
else
    export_term=${TERM:-xterm-256color}
    exec /usr/bin/sudo /usr/bin/lxc-attach -n "${PCTID}" \
        --clear-env --set-var TERM="${export_term}" \
        -- /bin/su - root
fi
