#!/bin/bash

if [ -f "$__object/parameter/userid" ]; then
   userid=$(cat "$__object/parameter/userid")
else
   userid="$__object_id"
fi

userdata=$(pveum user list --full | grep "^│ $userid " || true)

if test -n "$userdata"; then
   printf '%s' "$userdata"
else
   exit 0
fi
