#!/bin/bash

if [ -f "$__object/parameter/userid" ]; then
   userid=$(cat "$__object/parameter/userid")
else
   userid="$__object_id"
fi

userdata=$(pveum user list --full | grep "^│ $userid " || true)

if test -n "$userdata"; then
   email="$(echo "$userdata" | awk -F '│' '{print $4}' | awk '{print $1}')"
   enable="$(echo "$userdata" | awk -F '│' '{print $5}' | awk '{print $1}')"
   expire="$(echo "$userdata" | awk -F '│' '{print $6}' | awk '{print $1}')"
   firstname="$(echo "$userdata" | awk -F '│' '{print $7}' | awk '{$1=$1};1')"
   groups="$(echo "$userdata" | awk -F '│' '{print $8}' | awk '{$1=$1};1')"
   keys="$(echo "$userdata" | awk -F '│' '{print $9}' | awk '{print $1}')"
   lastname="$(echo "$userdata" | awk -F '│' '{print $10}' | awk '{$1=$1};1')"

   mkdir -p "$__object/explorer"

#   echo "$email" > /var/lib/cdist/conf/type/__proxmox-user/explorer/email
#   echo "$enable" > /var/lib/cdist/conf/type/__proxmox-user/explorer/enable
#   echo "$expire" > /var/lib/cdist/conf/type/__proxmox-user/explorer/expire
#   echo "$firstname" > /var/lib/cdist/conf/type/__proxmox-user/explorer/firstname
#   echo "$groups" > /var/lib/cdist/conf/type/__proxmox-user/explorer/groups
#   echo "$keys" > /var/lib/cdist/conf/type/__proxmox-user/explorer/keys
#   echo "$lastname" > /var/lib/cdist/conf/type/__proxmox-user/explorer/lastname

   state='present'
else
   state='absent'
fi

comment="$(echo "$userdata" | awk -F '│' '{print $3}' | awk '{$1=$1};1')"
echo "$comment" > "$__object/parameter/comment"

printf '%s' "$state"
