#!/bin/bash
set -e
name="efikernelhack"
base="/usr/share/${name}"
version="$1"
mkdir -p "$base"
for file in System.map- vmlinuz- initrd.img- config-; do
   dpkg-divert --package "$name" --rename --divert "$base"/"${file}${version}" /boot/"${file}${version}"
done
