#!/bin/sh

vars=$(cat $__object/parameter/vars | sed "s/,/ /g" )
if test -f "$__object/parameter/file"; then
   targetfile="$(cat "$__object/parameter/file")"
else
   targetfile="/$__object_id"
fi
jsfile=$(mktemp)
newfile=$(mktemp)

(
cat "$__type/files/pre.js"
cat "$__object/parameter/set" | sed "s/$/;/"
cat "$__type/files/post.js"
) > "$jsfile"
node "$jsfile" "$__object/explorer/file" $vars > "$newfile"
rm -f "$jsfile"
if !diff "$__object/explorer/file" "$newfile" > /dev/null; then
   echo "rm -f \"$targetfile\""
   echo "cat > \"$targetfile\" <<EOF"
   cat "$newfile"
   echo "EOF"
   test -f "$__object/parameter/onchange" && cat "$__object/parameter/onchange"
fi
rm -f "$newfile"
